import assert from 'node:assert/strict';
import { isPlaceholderColorCode, resolveImportColorLabels } from './importColorResolver.js';
import { buildAutoInternalCode, isAutoGeneratedInternalCode } from './importItemCodes.js';

assert.equal(isPlaceholderColorCode('#000000'), true);
assert.equal(isPlaceholderColorCode('ورق شجر'), false);

assert.deepEqual(
  resolveImportColorLabels({ colorName: 'فستقي', colorCode: 'ورق شجر' }),
  { nameAr: 'فستقي', nameTr: 'فستقي', colorCode: 'ورق شجر', supplierColorCode: '' },
);

assert.deepEqual(
  resolveImportColorLabels({ colorNameTr: 'BEJ', colorCode: '#000000' }),
  { nameAr: 'BEJ', nameTr: 'BEJ', colorCode: '', supplierColorCode: '' },
);

assert.deepEqual(
  resolveImportColorLabels({ colorName: 'فضي', colorCode: '' }),
  { nameAr: 'فضي', nameTr: 'فضي', colorCode: '', supplierColorCode: '' },
);

const auto = buildAutoInternalCode('Alexandra');
assert.equal(isAutoGeneratedInternalCode(auto), true);
assert.ok(auto.startsWith('IMP-AUTO-'));

console.log('importColorResolver.test.ts: OK');
