/** Internal codes generated when Excel leaves كود الخامة blank (not shown in UI). */
export const AUTO_INTERNAL_CODE_PREFIX = 'IMP-AUTO-';

export function isAutoGeneratedInternalCode(code: string | null | undefined): boolean {
  return String(code ?? '').trim().startsWith(AUTO_INTERNAL_CODE_PREFIX);
}

export function buildAutoInternalCode(slug: string): string {
  const base = String(slug || 'ITEM')
    .normalize('NFKD')
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48)
    .toUpperCase();
  return `${AUTO_INTERNAL_CODE_PREFIX}${base || 'ITEM'}`;
}
