import assert from 'node:assert/strict';
import {
  looksLikeUniqueDesignSku,
  resolveStockImportItemCodes,
} from './stockImportItemCodes.js';
import { isAutoGeneratedInternalCode } from './importItemCodes.js';

assert.equal(looksLikeUniqueDesignSku('Jakar'), false);
assert.equal(looksLikeUniqueDesignSku('Düz'), false);
assert.equal(looksLikeUniqueDesignSku('nw-48142'), true);
assert.equal(looksLikeUniqueDesignSku('kl-33'), true);
assert.equal(looksLikeUniqueDesignSku('v-12'), true);

const alexandra = resolveStockImportItemCodes('Alexandra', 'Jakar', 'aleppo_incoming_minimal');
assert.equal(alexandra.matchByCode, '');
assert.equal(alexandra.supplierCode, 'Jakar');
assert.equal(alexandra.designLabel, 'Jakar');
assert.equal(isAutoGeneratedInternalCode(alexandra.internalCode), true);

const moscow = resolveStockImportItemCodes('moscow dgtal', 'nw-48142', 'aleppo_incoming_minimal');
assert.equal(moscow.matchByCode, '');
assert.equal(moscow.internalCode, 'nw-48142');

const sharedDuzA = resolveStockImportItemCodes('Balksriti', 'Düz', 'aleppo_incoming_minimal');
const sharedDuzB = resolveStockImportItemCodes('Berlin sardonlu', 'Düz', 'aleppo_incoming_minimal');
assert.notEqual(sharedDuzA.internalCode, sharedDuzB.internalCode);
assert.equal(sharedDuzA.matchByCode, '');
assert.equal(sharedDuzB.matchByCode, '');

console.log('stockImportItemCodes.test.ts: OK');
