import assert from 'node:assert/strict';
import {
  looksLikeUniqueDesignSku,
  resolveStockImportItemCodes,
} from './stockImportItemCodes.js';
import { isAutoGeneratedInternalCode } from './importItemCodes.js';

assert.equal(looksLikeUniqueDesignSku('Jakar'), false);
assert.equal(looksLikeUniqueDesignSku('Düz'), false);
assert.equal(looksLikeUniqueDesignSku('nw-48142'), true);
assert.equal(looksLikeUniqueDesignSku('kl-33'), true);
assert.equal(looksLikeUniqueDesignSku('v-12'), true);
assert.equal(looksLikeUniqueDesignSku('8'), false);

const royal = resolveStockImportItemCodes('ROYAL MAX JAKAR', '8', 'supplier_invoice');
assert.equal(royal.matchByCode, '');
assert.equal(royal.supplierCode, null);
assert.equal(isAutoGeneratedInternalCode(royal.internalCode), true);

const alexandra = resolveStockImportItemCodes('Alexandra', 'Jakar', 'aleppo_incoming_minimal');
assert.equal(alexandra.matchByCode, '');
assert.equal(alexandra.supplierCode, null);
assert.equal(alexandra.designLabel, 'Jakar');
assert.equal(isAutoGeneratedInternalCode(alexandra.internalCode), true);

const moscow = resolveStockImportItemCodes('moscow dgtal', 'nw-48142', 'aleppo_incoming_minimal');
assert.equal(moscow.matchByCode, 'nw-48142');
assert.equal(moscow.internalCode, 'nw-48142');

const numericCode = resolveStockImportItemCodes('asya', '5114', 'aleppo_incoming_minimal');
assert.equal(numericCode.matchByCode, '5114');
assert.equal(numericCode.internalCode, '5114');

const sameNameOtherCode = resolveStockImportItemCodes('asya', '5011', 'aleppo_incoming_minimal');
assert.equal(sameNameOtherCode.matchByCode, '5011');
assert.notEqual(sameNameOtherCode.internalCode, numericCode.internalCode);

const sharedDuzA = resolveStockImportItemCodes('Balksriti', 'Düz', 'aleppo_incoming_minimal');
const sharedDuzB = resolveStockImportItemCodes('Berlin sardonlu', 'Düz', 'aleppo_incoming_minimal');
assert.notEqual(sharedDuzA.internalCode, sharedDuzB.internalCode);
assert.equal(sharedDuzA.matchByCode, '');
assert.equal(sharedDuzB.matchByCode, '');

console.log('stockImportItemCodes.test.ts: OK');
