/**
 * توليد مفاتيح تفعيل عبر CLI قبل تفعيل النظام (بدون تسجيل دخول ويب).
 * يستخدم نفس منطق الخادم: تجزئة SHA256 + pepper، جدول activation_keys، حدث KEY_GENERATED.
 *
 * الاستخدام:
 *   npm run activation:generate -- --count=20 --plan=FULL
 *   npm run activation:generate -- --count=3 --plan=FULL --expiresAt=2027-12-31 --notes="batch1"
 *   npm run activation:generate -- --output=server/generated/out.txt
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ActivationError,
  generateActivationKeys,
  type ActivationPlanCode,
} from '../services/activationService.js';
import { getEnv } from '../config/env.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const PLANS = new Set<ActivationPlanCode>(['LITE', 'PRO', 'FULL']);

function parseArgs(argv: string[]): Record<string, string | boolean> {
  const out: Record<string, string | boolean> = {};
  const positional: string[] = [];

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) {
      positional.push(a);
      continue;
    }
    const eq = a.indexOf('=');
    if (eq !== -1) {
      const key = a.slice(2, eq).trim();
      out[key] = a.slice(eq + 1).trim();
      continue;
    }
    const key = a.slice(2).trim();
    const next = argv[i + 1];
    if (next && !next.startsWith('--')) {
      out[key] = next;
      i += 1;
    } else {
      out[key] = 'true';
    }
  }

  /**
   * على Windows قد يمرّر npm الوسائط بشكل موضعي فقط، مثل:
   * `tsx ... 20 FULL` أو `... 1 LITE` أو `... LITE` فقط.
   */
  if (out.count === undefined && positional[0] && /^\d+$/.test(positional[0])) {
    out.count = positional[0];
  }
  if (
    out.plan === undefined &&
    positional[1] &&
    PLANS.has(String(positional[1]).toUpperCase() as ActivationPlanCode)
  ) {
    out.plan = String(positional[1]).toUpperCase();
  }
  if (
    out.plan === undefined &&
    positional.length === 1 &&
    PLANS.has(String(positional[0]).toUpperCase() as ActivationPlanCode)
  ) {
    out.plan = String(positional[0]).toUpperCase();
  }

  return out;
}

function pad2(n: number): string {
  return String(n).padStart(2, '0');
}

function timestampForFilename(d: Date): string {
  return (
    `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}-` +
    `${pad2(d.getHours())}${pad2(d.getMinutes())}${pad2(d.getSeconds())}`
  );
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  let count = 20;
  if (args.count !== undefined) {
    const n = Number(args.count);
    if (!Number.isFinite(n) || n < 1 || !Number.isInteger(n)) {
      console.error('[activation:generate] قيمة --count غير صالحة (عدد صحيح ≥ 1).');
      process.exit(1);
    }
    if (n > 100) {
      console.error('[activation:generate] رُفض الطلب: الحد الأقصى للعدد هو 100.');
      process.exit(1);
    }
    count = n;
  }

  let plan: ActivationPlanCode = 'FULL';
  if (args.plan !== undefined) {
    const p = String(args.plan).toUpperCase();
    if (!PLANS.has(p as ActivationPlanCode)) {
      console.error('[activation:generate] --plan يجب أن يكون LITE أو PRO أو FULL.');
      process.exit(1);
    }
    plan = p as ActivationPlanCode;
  }

  const expiresAt =
    args.expiresAt !== undefined && args.expiresAt !== ''
      ? String(args.expiresAt)
      : null;
  const notes =
    args.notes !== undefined && args.notes !== '' ? String(args.notes) : null;

  try {
    getEnv();
  } catch (e) {
    console.error('[activation:generate] فشل قراءة البيئة. تأكد من DATABASE_URL في server/.env');
    if (e instanceof Error) console.error(e.message);
    process.exit(1);
  }

  const pepper = process.env.ACTIVATION_KEY_PEPPER?.trim();
  if (!pepper) {
    console.error('[activation:generate] ACTIVATION_KEY_PEPPER غير معرّف في server/.env — مطلوب لتجزئة المفاتيح.');
    process.exit(1);
  }

  let keys: string[];
  try {
    keys = await generateActivationKeys(count, plan, null, {
      expiresAt,
      notes,
      eventMessage: 'key generated by admin CLI',
    });
  } catch (e) {
    if (e instanceof ActivationError) {
      console.error(`[activation:generate] ${e.message}`);
      process.exit(1);
    }
    throw e;
  }

  const generatedAt = new Date().toISOString();
  const projectRoot = path.resolve(__dirname, '../../..');
  const defaultDir = path.join(projectRoot, 'server', 'generated');
  const defaultFile = path.join(defaultDir, `activation-keys-${timestampForFilename(new Date())}.txt`);

  const outputPath =
    args.output !== undefined && String(args.output).trim() !== ''
      ? path.isAbsolute(String(args.output))
        ? String(args.output)
        : path.resolve(process.cwd(), String(args.output))
      : defaultFile;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const fileBody =
    [
      'CLOTEX — نسخة المالك لمفاتيح التفعيل (لا تُستخدم للتحقق المحلي)',
      `تاريخ التوليد: ${generatedAt}`,
      `الخطة: ${plan}`,
      notes ? `ملاحظات: ${notes}` : null,
      expiresAt ? `انتهاء المفتاح (اختياري في السجل): ${expiresAt}` : null,
      '',
      '---',
      '',
      ...keys,
      '',
      '---',
      '',
      'احفظ هذه المفاتيح في مكان آمن. لن تظهر مرة أخرى.',
      '',
    ]
      .filter((line) => line !== null)
      .join('\n');

  fs.writeFileSync(outputPath, fileBody, 'utf8');

  console.log('');
  console.log(`[activation:generate] تم توليد ${keys.length} مفتاحاً (${plan}).`);
  console.log('[activation:generate] المفاتيح الخام (مرة واحدة):');
  console.log('');
  for (const k of keys) {
    console.log(k);
  }
  console.log('');
  console.log(`[activation:generate] نُسخت أيضاً إلى: ${outputPath}`);
  console.log('[activation:generate] لا تُخزَّن المفاتيح الخام في git — المجلد server/generated/ مُهمل.');
  console.log('');
}

main().catch((e) => {
  console.error('[activation:generate] خطأ غير متوقع:', e);
  process.exit(1);
});
